In [31]:
import nltk
# nltk.download('brown')
# nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kushidhar/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [2]:
from nltk.corpus import brown

In [3]:
print(brown.categories())

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


In [4]:
data = brown.sents(categories='adventure')

In [5]:
print(' '.join(data[0]))

Dan Morgan told himself he would forget Ann Turner .


## Bag of words
- Get the Data/Corpus
- Tokenisation,Stopword Removal
- Stemming
- Building a vocab
- Vectorization
- Classification

In [6]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [8]:
document = """
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,
as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and
web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.
Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
"""

In [20]:
sentence = """Lorem Ipsum has been the industry's standard dummy text ever since 1,2,3 the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

In [14]:
sents = sent_tokenize(document)

In [26]:
# sents

In [21]:
word = word_tokenize(sentence)

In [24]:
# word
# sentence.split()

## Stopwords

In [48]:
from nltk.corpus import stopwords

In [230]:

sw = set(stopwords.words('english'))
len(sw)

179

In [75]:
def remove_stopwords(text):
    sws = set(stopwords.words('english'))
    negative_stopwords = ["against","aren", "aren't","couldn't","didn't","doesn",
        "doesn't","don","don't","hadn","hadn't","haven","haven't",
        "isn","isn't", "mightn","mightn't","mustn","mustn't","needn",
        "needn't","no","nor","not", "shan","shan't", "shouldn","shouldn't",
        "wasn","wasn't","weren","weren't","wouldn","wouldn't"]
    for word in negative_stopwords:
        sws.remove(word)
    text = word_tokenize(text)
    useful_words = [w for w in text if w not in sws]
    return useful_words

In [108]:
text = "i am not 12,3 cool and was't cool #not @guys"

In [87]:
# word_tokenize(text)
remove_stopwords(text)

['not', '12,3', 'cool', "was't", 'cool', 'not', 'guys']

In [229]:
len(negative_stopwords)

34

## Regex

In [88]:
from nltk.tokenize import RegexpTokenizer

<img src = "regex1.png"  width="400" height="600" align="left"/>
<img src = "regex2.png"  width="400" height="800" align="right"/>


<img src = "regex3.png"  width="400" height="600" align="left"/>
<img src = "regex4.png"  width="400" height="1000" align="right"/>

In [109]:
tokenizer = RegexpTokenizer("[a-zA-Z@'.]+")
useful_text = tokenizer.tokenize(text)

# Stemming
- process that transforms particular words(verbs,plurals) into their radical form
- preserve the semantics of the scentence without increasing the number of unique tokens
- ex : jumps,jumping,jumped,jump ==> jump

In [111]:
text = """The quick brown fox jumps over the lazy dog
"""

In [113]:
from nltk.stem.snowball import SnowballStemmer,PorterStemmer
from nltk.stem.lancaster import LancasterStemmer
# SnowballStemmer,PorterStemmer,LancasterStemmer

In [130]:
ps = PorterStemmer()
# avaliable in multi languages
ps.stem('బౌలర్లపై ద్రావిడ్ ప్రత్యేక దృష్టి')

'బౌలర్లపై ద్రావిడ్ ప్రత్యేక దృష్టి'

In [137]:
# only english ye mawa
ss = SnowballStemmer('english')
ss.stem('Cooling')

## Lematization

In [153]:
from nltk.stem import WordNetLemmatizer
wn = WordNetLemmatizer()
wn.lemmatize('em chestundho em ardham kavadam ledhu ద్రావిడ్')

'em chestundho em ardham kavadam ledhu ద్రావిడ్'

In [143]:
# nltk.download('wordnet')

# Building a Vocab and vectorization

In [170]:
corpus = [
    "At vero eos et accusamus et iusto odio dignissimos sentium voluptatum deleniti atqueerunt mollitia animi, id est laborum et dolorum fuga",
    " Et harum quidem rerum facilis est et expedita distinctio",
    " Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus",
    "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae",
    " Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat"
]

In [171]:
from sklearn.feature_extraction.text import CountVectorizer

In [172]:
cv = CountVectorizer()

In [173]:
vectorzed_corpus = cv.fit_transform(corpus)

In [174]:
len(vectorzed_corpus.toarray())


5

In [176]:
vectorzed_corpus.toarray()

array([[1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
        3, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        2, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        0, 1,

In [178]:
print(cv.vocabulary_)

{'at': 4, 'vero': 70, 'eos': 20, 'et': 22, 'accusamus': 0, 'iusto': 33, 'odio': 46, 'dignissimos': 14, 'sentium': 63, 'voluptatum': 73, 'deleniti': 13, 'atqueerunt': 5, 'mollitia': 40, 'animi': 2, 'id': 30, 'est': 21, 'laborum': 34, 'dolorum': 17, 'fuga': 27, 'harum': 28, 'quidem': 53, 'rerum': 60, 'facilis': 26, 'expedita': 24, 'distinctio': 15, 'nam': 41, 'libero': 35, 'tempore': 66, 'cum': 9, 'soluta': 65, 'nobis': 44, 'eligendi': 19, 'optio': 48, 'cumque': 10, 'nihil': 43, 'impedit': 31, 'quo': 54, 'minus': 38, 'quod': 55, 'maxime': 37, 'placeat': 50, 'facere': 25, 'possimus': 51, 'temporibus': 67, 'autem': 7, 'quibusdam': 52, 'aut': 6, 'officiis': 47, 'debitis': 11, 'necessitatibus': 42, 'saepe': 61, 'eveniet': 23, 'ut': 69, 'voluptates': 71, 'repudiandae': 59, 'sint': 64, 'molestiae': 39, 'non': 45, 'recusandae': 56, 'itaque': 32, 'earum': 18, 'hic': 29, 'tenetur': 68, 'sapiente': 62, 'delectus': 12, 'reiciendis': 57, 'voluptatibus': 72, 'maiores': 36, 'alias': 1, 'consequatur': 

In [184]:
len(vectorzed_corpus.toarray()[1])

74

In [188]:
vectorze_corpus =  vectorzed_corpus.toarray()

In [189]:
num = vectorze_corpus[2]

In [190]:
num

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0])

In [191]:
cv.inverse_transform(num)

[array(['cum', 'cumque', 'eligendi', 'est', 'facere', 'id', 'impedit',
        'libero', 'maxime', 'minus', 'nam', 'nihil', 'nobis', 'optio',
        'placeat', 'possimus', 'quo', 'quod', 'soluta', 'tempore'],
       dtype='<U14')]

In [201]:
randnums= np.random.randint(0,6,74)

In [202]:
import numpy as np

In [204]:
arr = cv.inverse_transform(randnums)

In [206]:
arr

[array(['accusamus', 'alias', 'animi', 'asperiores', 'at', 'atqueerunt',
        'aut', 'autem', 'cum', 'debitis', 'delectus', 'dignissimos',
        'distinctio', 'doloribus', 'dolorum', 'earum', 'eligendi', 'eos',
        'est', 'et', 'eveniet', 'expedita', 'facere', 'fuga', 'harum',
        'hic', 'id', 'impedit', 'iusto', 'laborum', 'maiores', 'maxime',
        'minus', 'molestiae', 'mollitia', 'nam', 'nihil', 'nobis', 'non',
        'odio', 'officiis', 'optio', 'perferendis', 'placeat', 'possimus',
        'quibusdam', 'quidem', 'quo', 'quod', 'recusandae', 'reiciendis',
        'repellat', 'repudiandae', 'rerum', 'saepe', 'sapiente', 'sentium',
        'sint', 'soluta', 'tempore', 'temporibus', 'tenetur', 'ut',
        'voluptatibus', 'voluptatum'], dtype='<U14')]

In [210]:
' '.join(arr[0])

'accusamus alias animi asperiores at atqueerunt aut autem cum debitis delectus dignissimos distinctio doloribus dolorum earum eligendi eos est et eveniet expedita facere fuga harum hic id impedit iusto laborum maiores maxime minus molestiae mollitia nam nihil nobis non odio officiis optio perferendis placeat possimus quibusdam quidem quo quod recusandae reiciendis repellat repudiandae rerum saepe sapiente sentium sint soluta tempore temporibus tenetur ut voluptatibus voluptatum'

In [216]:
def myTokenizer(document):
    
    words = tokenizer.tokenize(document.lower())
    # remove stopwords
    words = ' '.join(words)
    words = remove_stopwords(words)
    return words
        

In [218]:
sent = "jaii balayya jai jai balayya "

In [219]:
myTokenizer(sent)

['jaii', 'balayya', 'jai', 'jai', 'balayya']

In [220]:
cv = CountVectorizer(tokenizer = myTokenizer)

In [225]:
vectorized_corpus = cv.fit_transform(corpus).toarray()

In [228]:
len(vectorized_corpus[0])

73

In [235]:
test_corpus = ["Holaa animi lorem golla",]

In [236]:
cv.transform(test_corpus).toarray()

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0]])

## More ways to create features
- Unigram -every word as a feature
- Bigrams
- Trigrams
- n-grams
- TF-IDF Normalization

In [238]:
sent_1 = ["this is a good movie"]
sent_2 = ["this is not a good movie"]

In [251]:
cv = CountVectorizer(ngram_range=(1,3))

In [252]:
docs = [sent_1[0],sent_2[0]]

In [253]:
cv.fit_transform(docs).toarray()

array([[1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]])

In [254]:
cv.vocabulary_

{'this': 11,
 'is': 2,
 'good': 0,
 'movie': 7,
 'this is': 12,
 'is good': 3,
 'good movie': 1,
 'this is good': 13,
 'is good movie': 4,
 'not': 8,
 'is not': 5,
 'not good': 9,
 'this is not': 14,
 'is not good': 6,
 'not good movie': 10}

## TF-IDF Normalisation
- avoids features that occur very often,because they contains less information
- information decreases as the number of occurances accross diffrent type os documents
- so we define another term - term-document-frequency which associated a weight with every term

In [268]:
sent_1 = "this is good movie"
sent_2 = "this was good movie"
sent_3 = "this is not a good movie"
docs = [sent_1,sent_2,sent_3]

In [269]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [270]:
tfidf = TfidfVectorizer()

In [271]:
vc = tfidf.fit_transform(docs).toarray()

In [279]:
max(vc[1])

0.6990303272568005

In [280]:
vc

array([[0.46333427, 0.59662724, 0.46333427, 0.        , 0.46333427,
        0.        ],
       [0.41285857, 0.        , 0.41285857, 0.        , 0.41285857,
        0.69903033],
       [0.3645444 , 0.46941728, 0.3645444 , 0.61722732, 0.3645444 ,
        0.        ]])

In [281]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}